### ISSUE TITLE
Support "streaming" results during query execution

### ISSUE THREAD

**Issue by alamb** [influxdata/influxdb_iox#503]
__Use case:__
At the time of writing, when responding to gRPC queries, IOx will effectively produce a single `ReadResponse` per measurement. This means that all the series / data for that measurement is buffered in memory and sent in a big chunk back to the client

This has several negative properties:
1. Increased resource usage: consumes more memory than necessary, both to buffer the intermediate results of the plan as well as the data coverson / network mesage.  
2. Increased Latency / loss of streaming: It delays any data from being sent until the entire result is converted

__Proposal:__
The high level proposal is to "stream" results back to the client as they are created. The underlying DataFusion executor supports streaming but we buffer the results (twice, actually) before sending them back, for implementation convenience. 

__Current behaviour:__
The buffering happens at two levels today:
1. The results of the DataFusion plan (`RecordBatch`es are collected -- calls to `collect` in exec.rs -- for example,  https://github.com/influxdata/influxdb_iox/blob/main/query/src/exec.rs#L363)

2. When converting RecordBatches --> gRPC data frames, data for all series (aka all columns) is collected into a `Vec` before being converted

Namely, 
```
pub fn series_set_item_to_read_response(series_set_item: SeriesSetItem) -> Result<ReadResponse> {
```
in https://github.com/influxdata/influxdb_iox/blob/main/src/server/rpc/data.rs#L88

__Desired behaviour:__
As data flows back from the DataFusion plan, it should be converted to SeriesSets, and as soon as the next group is seen, the series set should be produced. 

Also, once that SeriesSet is produced, then it should immediately be converted to the gRPC data frames and returned to the client before the next chunk of data (`RecordBatch`) from DataFusion is requested. 

Note this ticket might be best implemented in several chinks

__Alternatives considered:__
Describe other solutions or features you considered.

**Comment by ming535** [comment]
It seems that this issue was already solved?
`Executor::to_series_set` spawns one task for each logical plan. 
For each of the above task, it execute the plan and streams `SendableRecordBatchStream` to `SeriesSetItem`.
`Executor::to_series_set` receives each task's `SeriesSetItem` and sends it to `rps::service`.
`rpc::service::convertt_seriess_set` streams `SeriesSetItem` to `ReadResponse`

**Comment by alamb** [comment]
Hi @ming535  -- 

The specific buffering I am thinking about in this task is here:

https://github.com/influxdata/influxdb_iox/blob/99605b27d77ceac665d01e128fe292ef6e0d6301/query/src/exec.rs#L402-L427

https://github.com/influxdata/influxdb_iox/blob/99605b27d77ceac665d01e128fe292ef6e0d6301/query/src/exec.rs#L364-L371

Which basically both get a `SendableRecordBatchStream` (which is a handle to get streaming results of the datafusion plan) but then `collect` them all into a `Vec<RecordBatch>` before processing that vec one at a time and sending the results out.

However, you are right that the main `read_filter` and `read_group` paths that use the SeriesSetConverter does process batches one at a time in a streaming fashion `https://github.com/influxdata/influxdb_iox/blob/99605b27d77ceac665d01e128fe292ef6e0d6301/query/src/exec/seriesset.rs#L186-L195`

**Comment by alamb** [comment]
This has been partly completed (mostly with the introduction of the table provider https://github.com/influxdata/influxdb_iox/pull/730). THe buffering in exec still happens I think, however
